"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Box, Toolbar } from '@mui/material'
import DrawerAppBar from '@/components/NavBar'


import { createStyles, makeStyles } from '@mui/styles';
import { createTheme, Theme, ThemeProvider } from '@mui/material/styles';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({

  }),
);

const theme = createTheme({
  palette: {
     primary: {
        main: '#1976d2',
     },
  },
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //const classes = useStyles();

  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>
          <Box sx={{ height: "100vh", display: "flex", flexDirection: 'column' }}>
            <DrawerAppBar />
            <Toolbar />
            <Box sx={{ flexGrow: 1 }}>
              {children}
            </Box>
          </Box>
        </body>
      </ThemeProvider>
    </html>
  )
}
